<?php

namespace RedditBotAlpha\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 20:38:23.
 */
class ListingTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Listing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Listing;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::getBefore
     * @todo   Implement testGetBefore().
     */
    public function testGetBefore() {
        $value = '123456';
        $this->object->setBefore($value);
        $this->assertEquals($value, $this->object->getBefore());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::setBefore
     * @todo   Implement testSetBefore().
     */
    public function testSetBefore() {
        $value = '123456';
        $this->object->setBefore($value);
        $this->assertEquals($value, $this->object->getBefore());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::getAfter
     * @todo   Implement testGetAfter().
     */
    public function testGetAfter() {
        $value = '123456';
        $this->object->setAfter($value);
        $this->assertEquals($value, $this->object->getAfter());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::setAfter
     * @todo   Implement testSetAfter().
     */
    public function testSetAfter() {
        $value = '123456';
        $this->object->setAfter($value);
        $this->assertEquals($value, $this->object->getAfter());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::getModhash
     * @todo   Implement testGetModhash().
     */
    public function testGetModhash() {
        $modhash = 'y581uf36ho6d2c6d8863d0d8517122e8491bde89ccafd8e7b1';
        $this->object->setModhash($modhash);
        $this->assertEquals($modhash, $this->object->getModhash());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::setModhash
     * @todo   Implement testSetModhash().
     */
    public function testSetModhash() {
        $modhash = 'y581uf36ho6d2c6d8863d0d8517122e8491bde89ccafd8e7b1';
        $this->object->setModhash($modhash);
        $this->assertEquals($modhash, $this->object->getModhash());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        $data = array('foo' => 'bar', 'baz' => 'bat');
        $this->object->setData($data);
        $this->assertSame($data, $this->object->getData());
    }

    /**
     * @covers RedditBotAlpha\Model\Listing::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        $data = array('foo' => 'bar', 'baz' => 'bat');
        $this->object->setData($data);
        $this->assertSame($data, $this->object->getData());
    }
}
