<?php

namespace RedditBotAlpha\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 20:38:22.
 */
class ThingTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Thing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Thing;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getUps
     * @todo   Implement testGetUps().
     */
    public function testGetUps() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setUps
     * @todo   Implement testSetUps().
     */
    public function testSetUps() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getDowns
     * @todo   Implement testGetDowns().
     */
    public function testGetDowns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setDowns
     * @todo   Implement testSetDowns().
     */
    public function testSetDowns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getLikes
     * @todo   Implement testGetLikes().
     */
    public function testGetLikes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setLikes
     * @todo   Implement testSetLikes().
     */
    public function testSetLikes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getCreatedUtc
     * @todo   Implement testGetCreatedUtc().
     */
    public function testGetCreatedUtc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setCreatedUtc
     * @todo   Implement testSetCreatedUtc().
     */
    public function testSetCreatedUtc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getKind
     * @todo   Implement testGetKind().
     */
    public function testGetKind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setKind
     * @todo   Implement testSetKind().
     */
    public function testSetKind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
