<?php

namespace RedditBotAlpha\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-29 at 22:25:03.
 */
class AbstractServiceClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractServiceClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractServiceClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::hydrate
     * @todo   Implement testHydrate().
     */
    public function testHydrate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::getModel
     * @todo   Implement testGetModel().
     */
    public function testGetModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::setModel
     * @todo   Implement testSetModel().
     */
    public function testSetModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::getHydrator
     * @todo   Implement testGetHydrator().
     */
    public function testGetHydrator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::setHydrator
     * @todo   Implement testSetHydrator().
     */
    public function testSetHydrator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::getTableGateway
     * @todo   Implement testGetTableGateway().
     */
    public function testGetTableGateway()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\AbstractServiceClass::setTableGateway
     * @todo   Implement testSetTableGateway().
     */
    public function testSetTableGateway()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
