<?php

namespace RedditBotAlpha\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-29 at 22:25:02.
 */
class ListingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Listing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Listing;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}
