<?php

namespace RedditBotAlpha\Model\Thing;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-29 at 22:25:03.
 */
class AccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Account
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Account;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getCommentKarma
     * @todo   Implement testGetCommentKarma().
     */
    public function testGetCommentKarma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setCommentKarma
     * @todo   Implement testSetCommentKarma().
     */
    public function testSetCommentKarma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getCreated
     * @todo   Implement testGetCreated().
     */
    public function testGetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setCreated
     * @todo   Implement testSetCreated().
     */
    public function testSetCreated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getCreatedUtc
     * @todo   Implement testGetCreatedUtc().
     */
    public function testGetCreatedUtc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setCreatedUtc
     * @todo   Implement testSetCreatedUtc().
     */
    public function testSetCreatedUtc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getHasMail
     * @todo   Implement testGetHasMail().
     */
    public function testGetHasMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setHasMail
     * @todo   Implement testSetHasMail().
     */
    public function testSetHasMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getHasModMail
     * @todo   Implement testGetHasModMail().
     */
    public function testGetHasModMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setHasModMail
     * @todo   Implement testSetHasModMail().
     */
    public function testSetHasModMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getIsGold
     * @todo   Implement testGetIsGold().
     */
    public function testGetIsGold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setIsGold
     * @todo   Implement testSetIsGold().
     */
    public function testSetIsGold()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getIsMod
     * @todo   Implement testGetIsMod().
     */
    public function testGetIsMod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setIsMod
     * @todo   Implement testSetIsMod().
     */
    public function testSetIsMod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getLinkKarma
     * @todo   Implement testGetLinkKarma().
     */
    public function testGetLinkKarma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setLinkKarma
     * @todo   Implement testSetLinkKarma().
     */
    public function testSetLinkKarma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getModhash
     * @todo   Implement testGetModhash().
     */
    public function testGetModhash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setModhash
     * @todo   Implement testSetModhash().
     */
    public function testSetModhash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Account::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
