<?php

namespace RedditBotAlpha\Model\Thing;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-29 at 22:25:03.
 */
class SubredditTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Subreddit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Subreddit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::getDisplayName
     * @todo   Implement testGetDisplayName().
     */
    public function testGetDisplayName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::setDisplayName
     * @todo   Implement testSetDisplayName().
     */
    public function testSetDisplayName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::getOver18
     * @todo   Implement testGetOver18().
     */
    public function testGetOver18()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::setOver18
     * @todo   Implement testSetOver18().
     */
    public function testSetOver18()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::getSubscribers
     * @todo   Implement testGetSubscribers().
     */
    public function testGetSubscribers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::setSubscribers
     * @todo   Implement testSetSubscribers().
     */
    public function testSetSubscribers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::getUrl
     * @todo   Implement testGetUrl().
     */
    public function testGetUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Model\Thing\Subreddit::setUrl
     * @todo   Implement testSetUrl().
     */
    public function testSetUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
