<?php

namespace RedditBotAlpha\Service\Api;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 20:38:39.
 */
class AbstractApiClassTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractApiClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractApiClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::call
     * @todo   Implement testCall().
     */
    public function testCall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getHttpClient
     * @todo   Implement testGetHttpClient().
     */
    public function testGetHttpClient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setHttpClient
     * @todo   Implement testSetHttpClient().
     */
    public function testSetHttpClient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getPost
     * @todo   Implement testGetPost().
     */
    public function testGetPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setPost
     * @todo   Implement testSetPost().
     */
    public function testSetPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::addPostVariable
     * @todo   Implement testAddPostVariable().
     */
    public function testAddPostVariable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getRawResponse
     * @todo   Implement testGetRawResponse().
     */
    public function testGetRawResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setRawResponse
     * @todo   Implement testSetRawResponse().
     */
    public function testSetRawResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getDecodedResponse
     * @todo   Implement testGetDecodedResponse().
     */
    public function testGetDecodedResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setDecodedResponse
     * @todo   Implement testSetDecodedResponse().
     */
    public function testSetDecodedResponse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getSm
     * @todo   Implement testGetSm().
     */
    public function testGetSm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setSm
     * @todo   Implement testSetSm().
     */
    public function testSetSm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getConfig
     * @todo   Implement testGetConfig().
     */
    public function testGetConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setConfig
     * @todo   Implement testSetConfig().
     */
    public function testSetConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getProtocol
     * @todo   Implement testGetProtocol().
     */
    public function testGetProtocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setProtocol
     * @todo   Implement testSetProtocol().
     */
    public function testSetProtocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setPath
     * @todo   Implement testSetPath().
     */
    public function testSetPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::getBaseUrl
     * @todo   Implement testGetBaseUrl().
     */
    public function testGetBaseUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Service\Api\AbstractApiClass::setBaseUrl
     * @todo   Implement testSetBaseUrl().
     */
    public function testSetBaseUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
