<?php

namespace RedditBotAlpha\Storage;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-29 at 22:25:01.
 */
class ModhashTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Modhash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Modhash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers RedditBotAlpha\Storage\Modhash::storeModhash
     * @todo   Implement testStoreModhash().
     */
    public function testStoreModhash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Storage\Modhash::initTable
     * @todo   Implement testInitTable().
     */
    public function testInitTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Storage\Modhash::getModhash
     * @todo   Implement testGetModhash().
     */
    public function testGetModhash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
