<?php

namespace RedditBotAlpha\Storage;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-30 at 20:38:28.
 */
class AbstractStorageTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractStorage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractStorage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RedditBotAlpha\Storage\AbstractStorage::getAdapter
     * @todo   Implement testGetAdapter().
     */
    public function testGetAdapter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RedditBotAlpha\Storage\AbstractStorage::setAdapter
     * @todo   Implement testSetAdapter().
     */
    public function testSetAdapter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
